site :opscode

metadata

cookbook 'rbenv', :git => 'git@github.com:fnichol/chef-rbenv.git', :branch => 'v0.7.2'
#cookbook 'rbenv', :git => 'git@github.com:fnichol/chef-rbenv.git'
cookbook 'deploy_key', :git => 'git@github.com:cassianoleal/cookbook-deploy_key.git', :branch => '0.1.0'

cookbook 'chef-server', git: 'git://github.com/opscode-cookbooks/chef-server.git'

cookbook 'java'
